import type { Wine } from "./types";

export const wines: Wine[] = [
  {
    slug: "midnight-pinot-noir",
    name: "Midnight Pinot Noir",
    producer: "Maison Aurelle",
    type: "Red",
    region: "Burgundy",
    country: "France",
    grape: ["Pinot Noir"],
    vintage: 2022,
    priceGlass: 1250,
    priceBottle: 6800,
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1400&q=90",
    body: "Light",
    sweetness: "Dry",
    acidity: 4,
    tannin: 2,
    notes: ["cherry", "forest floor", "rose", "soft spice"],
    description: "Silky, fragrant red with lifted cherry fruit and savoury earth.",
    featured: true,
    sommelierChoice: true,
    pairWith: ["ember-duck", "forest-mushroom"],
  },
  {
    slug: "river-stone-chablis",
    name: "River Stone Chablis",
    producer: "Domaine Valmere",
    type: "White",
    region: "Chablis",
    country: "France",
    grape: ["Chardonnay"],
    vintage: 2023,
    priceGlass: 1350,
    priceBottle: 7200,
    image: "https://images.unsplash.com/photo-1474722883778-792e7990302f?auto=format&fit=crop&w=1400&q=90",
    body: "Light",
    sweetness: "Dry",
    acidity: 5,
    tannin: 1,
    notes: ["lemon", "chalk", "green apple", "oyster shell"],
    description: "Tense and mineral with citrus brightness and a clean saline finish.",
    featured: true,
    sommelierChoice: true,
    pairWith: ["charred-scallop", "line-caught-seabass"],
  },
  {
    slug: "golden-chenin",
    name: "Golden Chenin",
    producer: "Cape Ember",
    type: "White",
    region: "Stellenbosch",
    country: "South Africa",
    grape: ["Chenin Blanc"],
    vintage: 2022,
    priceGlass: 950,
    priceBottle: 4900,
    image: "https://images.unsplash.com/photo-1569919659476-f0852f6834b7?auto=format&fit=crop&w=1400&q=90",
    body: "Medium",
    sweetness: "Dry",
    acidity: 4,
    tannin: 1,
    notes: ["quince", "yellow apple", "beeswax", "ginger"],
    description: "Textured white with orchard fruit, gentle spice and bright acidity.",
    pairWith: ["tandoor-celeriac", "pumpkin-ravioli"],
  },
  {
    slug: "wild-herb-sauvignon",
    name: "Wild Herb Sauvignon",
    producer: "Cloudline Estate",
    type: "White",
    region: "Marlborough",
    country: "New Zealand",
    grape: ["Sauvignon Blanc"],
    vintage: 2024,
    priceGlass: 850,
    priceBottle: 4200,
    image: "https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?auto=format&fit=crop&w=1400&q=90",
    body: "Light",
    sweetness: "Dry",
    acidity: 5,
    tannin: 1,
    notes: ["lime", "gooseberry", "fresh herbs", "grapefruit"],
    description: "Vivid, aromatic and energetic with green citrus and herb notes.",
    pairWith: ["green-garden", "tomato-burrata"],
  },
  {
    slug: "ember-syrah",
    name: "Ember Syrah",
    producer: "Terra Noire",
    type: "Red",
    region: "Northern Rhône",
    country: "France",
    grape: ["Syrah"],
    vintage: 2021,
    priceGlass: 1450,
    priceBottle: 7900,
    image: "https://images.unsplash.com/photo-1473973266408-ed4e27abdd47?auto=format&fit=crop&w=1400&q=90",
    body: "Full",
    sweetness: "Dry",
    acidity: 3,
    tannin: 4,
    notes: ["blackberry", "pepper", "violet", "smoke"],
    description: "Dark-fruited and peppery with savoury smoke and structured tannin.",
    sommelierChoice: true,
    pairWith: ["lamb-saddle", "short-rib"],
  },
  {
    slug: "velvet-cabernet",
    name: "Velvet Cabernet",
    producer: "North Ridge Cellars",
    type: "Red",
    region: "Napa Valley",
    country: "USA",
    grape: ["Cabernet Sauvignon"],
    vintage: 2020,
    priceBottle: 9800,
    image: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1400&q=90",
    body: "Full",
    sweetness: "Dry",
    acidity: 3,
    tannin: 5,
    notes: ["cassis", "cedar", "cocoa", "graphite"],
    description: "Powerful but polished Cabernet with dark fruit and long savoury structure.",
    rare: true,
    pairWith: ["short-rib", "lamb-saddle"],
  },
  {
    slug: "rose-dawn",
    name: "Rosé Dawn",
    producer: "Clos Lumière",
    type: "Rosé",
    region: "Provence",
    country: "France",
    grape: ["Grenache", "Cinsault"],
    vintage: 2024,
    priceGlass: 800,
    priceBottle: 3900,
    image: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?auto=format&fit=crop&w=1400&q=90",
    body: "Light",
    sweetness: "Dry",
    acidity: 4,
    tannin: 1,
    notes: ["strawberry", "peach skin", "citrus", "herbs"],
    description: "Pale, dry rosé with delicate red fruit and a clean herbal finish.",
    pairWith: ["tomato-burrata", "ember-cauliflower"],
  },
  {
    slug: "silver-brut",
    name: "Silver Brut",
    producer: "Maison Clarette",
    type: "Sparkling",
    region: "Champagne",
    country: "France",
    grape: ["Chardonnay", "Pinot Noir"],
    vintage: "NV",
    priceGlass: 1600,
    priceBottle: 9200,
    image: "https://images.unsplash.com/photo-1547595628-c61a29f496f0?auto=format&fit=crop&w=1400&q=90",
    body: "Medium",
    sweetness: "Dry",
    acidity: 5,
    tannin: 1,
    notes: ["lemon curd", "brioche", "white flowers", "chalk"],
    description: "Fine bubbles, citrus precision and brioche depth for celebration or food.",
    featured: true,
    sommelierChoice: true,
    pairWith: ["charred-scallop", "river-trout"],
  },
  {
    slug: "alpine-gruner",
    name: "Alpine Grüner",
    producer: "Wachau Field",
    type: "White",
    region: "Wachau",
    country: "Austria",
    grape: ["Grüner Veltliner"],
    vintage: 2023,
    priceGlass: 900,
    priceBottle: 4500,
    image: "https://images.unsplash.com/photo-1516594915697-87eb3b1c14ea?auto=format&fit=crop&w=1400&q=90",
    body: "Light",
    sweetness: "Dry",
    acidity: 5,
    tannin: 1,
    notes: ["pear", "white pepper", "lime", "green herbs"],
    description: "Peppery, bright and food-friendly with crisp orchard fruit.",
    pairWith: ["ember-cauliflower", "green-garden"],
  },
  {
    slug: "amber-viognier",
    name: "Amber Viognier",
    producer: "Sunfold Estate",
    type: "White",
    region: "Adelaide Hills",
    country: "Australia",
    grape: ["Viognier"],
    vintage: 2022,
    priceGlass: 1000,
    priceBottle: 5100,
    image: "https://images.unsplash.com/photo-1506377585622-bedcbb027afc?auto=format&fit=crop&w=1400&q=90",
    body: "Full",
    sweetness: "Dry",
    acidity: 3,
    tannin: 1,
    notes: ["apricot", "jasmine", "ginger", "peach"],
    description: "Perfumed and generous with stone fruit and soft spice.",
    pairWith: ["pumpkin-ravioli", "tandoor-celeriac"],
  },
  {
    slug: "honeyed-sauternes",
    name: "Honeyed Sauternes",
    producer: "Château Doré",
    type: "Dessert",
    region: "Bordeaux",
    country: "France",
    grape: ["Sémillon", "Sauvignon Blanc"],
    vintage: 2019,
    priceGlass: 1100,
    priceBottle: 6400,
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1400&q=90",
    body: "Full",
    sweetness: "Sweet",
    acidity: 4,
    tannin: 1,
    notes: ["honey", "apricot", "orange peel", "saffron"],
    description: "Lush dessert wine balanced by bright acidity and citrus peel.",
    pairWith: ["burnt-honey", "mango-saffron"],
  },
  {
    slug: "old-vine-port",
    name: "Old Vine Tawny",
    producer: "Casa Vermelho",
    type: "Dessert",
    region: "Douro",
    country: "Portugal",
    grape: ["Touriga Nacional", "Touriga Franca"],
    vintage: "NV",
    priceGlass: 950,
    priceBottle: 5400,
    image: "https://images.unsplash.com/photo-1547595628-c61a29f496f0?auto=format&fit=crop&w=1400&q=90",
    body: "Full",
    sweetness: "Sweet",
    acidity: 3,
    tannin: 2,
    notes: ["walnut", "fig", "caramel", "orange zest"],
    description: "Nutty, mellow and rich with dried fruit and caramel complexity.",
    rare: true,
    pairWith: ["dark-chocolate", "burnt-honey"],
  },
];

export const wineRegions = [...new Set(wines.map((wine) => wine.region))].sort();

export function getWine(slug: string) {
  return wines.find((wine) => wine.slug === slug);
}
