"use client";
import { useEffect,useRef,useState,useSyncExternalStore } from "react";
import type { Lang,Message,Reply } from "@/lib/concierge/types";
import { conciergeStore } from "@/lib/concierge/storage";
import { replyTo } from "@/lib/concierge/engine";
import ChatMessage from "./ChatMessage"; import ChatComposer from "./ChatComposer"; import QuickPrompts from "./QuickPrompts"; import TypingIndicator from "./TypingIndicator"; import LanguageToggle from "./LanguageToggle"; import AIStatusBadge from "./AIStatusBadge"; import AssistantWelcome from "./AssistantWelcome";
export default function ChatPanel(){const messages=useSyncExternalStore(conciergeStore.subscribe,conciergeStore.getSnapshot,conciergeStore.getServerSnapshot);const [lang,setLang]=useState<Lang>("en"),[thinking,setThinking]=useState(false),[links,setLinks]=useState<Record<string,Reply["links"]>>({});const bottom=useRef<HTMLDivElement|null>(null);useEffect(()=>bottom.current?.scrollIntoView({behavior:"smooth"}),[messages,thinking]);
async function send(text:string){const u:Message={id:`U-${Date.now()}`,role:"user",text,createdAt:new Date().toISOString()};conciergeStore.add(u);setThinking(true);let r:Reply;try{const res=await fetch("/api/concierge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,lang})});if(!res.ok)throw new Error();r=await res.json();}catch{r=replyTo(text,lang);}const a:Message={id:`A-${Date.now()}`,role:"assistant",text:r.text,createdAt:new Date().toISOString()};conciergeStore.add(a);setLinks(x=>({...x,[a.id]:r.links}));setThinking(false);}
return <div className="grid gap-4 lg:grid-cols-[300px_1fr]"><aside className="space-y-3"><AssistantWelcome lang={lang}/><div className="rounded-[22px] bg-[#fffaf4] p-4"><div className="flex items-center justify-between gap-2"><AIStatusBadge/><LanguageToggle value={lang} onChange={setLang}/></div><button type="button" onClick={()=>conciergeStore.clear()} className="mt-4 w-full rounded-[14px] border border-[#4a3025]/10 px-3 py-3 text-[8px] uppercase tracking-[.11em] text-[#7c241e]">Clear chat</button></div></aside><div className="flex min-h-[68dvh] flex-col overflow-hidden rounded-[28px] border border-[#4a3025]/10 bg-[#efe6dd]"><div className="border-b border-[#4a3025]/8 p-3"><QuickPrompts lang={lang} onPick={send}/></div><div className="flex-1 space-y-3 overflow-y-auto p-3 md:p-5">{messages.length?messages.slice(-30).map(m=><ChatMessage key={m.id} message={m} links={links[m.id]||[]}/>):<div className="grid min-h-[320px] place-items-center text-center"><div><p className="text-4xl">✦</p><p className="lx-serif mt-3 text-3xl">{lang==="hi"?"कुछ पूछिए।":"Ask me anything."}</p></div></div>}{thinking?<TypingIndicator/>:null}<div ref={bottom}/></div><div className="border-t border-[#4a3025]/8 bg-[#fffaf4] p-3"><ChatComposer lang={lang} disabled={thinking} onSend={send}/></div></div></div>;}
