import type { Review } from "./types";

export const seedReviews: Review[] = [
  {
    id: "seed-1",
    name: "Aarav S.",
    city: "Indore",
    rating: 5,
    category: "Dining",
    title: "Beautiful pacing and detail",
    text: "The tasting menu felt considered from the first bite to dessert. Service was calm and the room never felt rushed.",
    visitDate: "2026-08-02",
    verified: true,
    featured: true,
    createdAt: "2026-08-03T12:00:00.000Z",
  },
  {
    id: "seed-2",
    name: "Meera K.",
    city: "Bhopal",
    rating: 5,
    category: "Wine",
    title: "Sommelier pairing was the highlight",
    text: "The wine suggestions were easy to understand and matched the food without overpowering it.",
    visitDate: "2026-07-28",
    verified: true,
    featured: true,
    createdAt: "2026-07-29T10:00:00.000Z",
  },
  {
    id: "seed-3",
    name: "Rohan M.",
    city: "Ujjain",
    rating: 4,
    category: "Service",
    title: "Warm and polished",
    text: "Staff remembered our anniversary note and handled the evening with a personal touch.",
    visitDate: "2026-07-21",
    verified: true,
    createdAt: "2026-07-22T09:00:00.000Z",
  },
  {
    id: "seed-4",
    name: "Ananya P.",
    city: "Indore",
    rating: 5,
    category: "Private Dining",
    title: "Private room felt special",
    text: "The room setup and pacing worked well for our family celebration. The event flow felt premium.",
    visitDate: "2026-07-14",
    verified: true,
    featured: true,
    createdAt: "2026-07-15T11:00:00.000Z",
  },
  {
    id: "seed-5",
    name: "Kabir J.",
    city: "Dewas",
    rating: 4,
    category: "Events",
    title: "Great chef collaboration night",
    text: "The one-night menu had strong energy and a few memorable courses. I would book another event.",
    visitDate: "2026-07-05",
    verified: true,
    createdAt: "2026-07-06T08:30:00.000Z",
  },
  {
    id: "seed-6",
    name: "Ishita R.",
    city: "Indore",
    rating: 5,
    category: "Dining",
    title: "A proper occasion restaurant",
    text: "The atmosphere, lighting and dessert finish made the evening feel like a complete experience.",
    visitDate: "2026-06-29",
    verified: true,
    createdAt: "2026-06-30T13:30:00.000Z",
  },
];

export const socialStats = [
  { label: "Demo guest rating", value: "4.8/5" },
  { label: "Featured reviews", value: "6+" },
  { label: "Saved favourites", value: "Local" },
  { label: "Response goal", value: "<24h" },
];
