import type { Dish, MenuCategory } from "./types";

export const menuCategories: MenuCategory[] = [
  "Starters",
  "From the Fire",
  "Mains",
  "Desserts",
];

export const dishes: Dish[] = [
  {
    slug: "charred-scallop",
    name: "Charred Scallop",
    category: "Starters",
    description: "Sweet scallop, cauliflower cream, kokum glaze and smoked almond.",
    ingredients: ["scallop", "cauliflower", "kokum", "almond", "brown butter"],
    price: 1450,
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1400&q=90",
    dietary: ["Gluten Free", "Contains Nuts"],
    spice: 1,
    calories: 330,
    protein: 28,
    chefChoice: true,
    bestseller: true,
    winePairing: { name: "Chablis", note: "Mineral acidity keeps the scallop bright." },
  },
  {
    slug: "ember-cauliflower",
    name: "Ember Cauliflower",
    category: "Starters",
    description: "Whole-roasted cauliflower, cashew cream, curry leaf oil and grapes.",
    ingredients: ["cauliflower", "cashew", "curry leaf", "grapes", "lime"],
    price: 1050,
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1400&q=90",
    dietary: ["Vegetarian", "Vegan", "Gluten Free", "Contains Nuts"],
    spice: 1,
    calories: 410,
    protein: 13,
    newDish: true,
    winePairing: { name: "Grüner Veltliner", note: "Peppery freshness works with curry leaf." },
  },
  {
    slug: "forest-mushroom",
    name: "Forest Mushroom",
    category: "Starters",
    description: "Roasted mushrooms, morel tea, black garlic and hazelnut.",
    ingredients: ["mushroom", "morel", "black garlic", "hazelnut"],
    price: 1250,
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1400&q=90",
    dietary: ["Vegetarian", "Gluten Free", "Contains Nuts"],
    spice: 0,
    calories: 360,
    protein: 15,
    winePairing: { name: "Pinot Noir", note: "Earthy fruit mirrors the mushroom depth." },
  },
  {
    slug: "tomato-burrata",
    name: "Tomato & Burrata",
    category: "Starters",
    description: "Heirloom tomato, burrata, basil oil, chilli pollen and aged balsamic.",
    ingredients: ["tomato", "burrata", "basil", "balsamic"],
    price: 1100,
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=1400&q=90",
    dietary: ["Vegetarian", "Gluten Free"],
    spice: 1,
    calories: 390,
    protein: 18,
    bestseller: true,
    winePairing: { name: "Rosé", note: "Dry red-fruit freshness loves tomato and basil." },
  },
  {
    slug: "river-trout",
    name: "River Trout",
    category: "From the Fire",
    description: "Fire-roasted trout, fennel, saffron whey and preserved lemon.",
    ingredients: ["trout", "fennel", "saffron", "whey", "lemon"],
    price: 1750,
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=1400&q=90",
    dietary: ["Gluten Free"],
    spice: 1,
    calories: 520,
    protein: 46,
    chefChoice: true,
    bestseller: true,
    winePairing: { name: "Albariño", note: "Saline citrus notes lift saffron and preserved lemon." },
  },
  {
    slug: "ember-duck",
    name: "Ember Duck",
    category: "From the Fire",
    description: "Coal-roasted duck breast, plum, chicory and five-spice jus.",
    ingredients: ["duck", "plum", "chicory", "five spice"],
    price: 2050,
    image: "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1400&q=90",
    dietary: ["Gluten Free"],
    spice: 2,
    calories: 640,
    protein: 49,
    chefChoice: true,
    winePairing: { name: "Pinot Noir", note: "Silky red fruit follows the plum without overpowering duck." },
  },
  {
    slug: "lamb-saddle",
    name: "Lamb Saddle",
    category: "From the Fire",
    description: "Pink lamb saddle, carrot, cumin, burnt honey and rosemary jus.",
    ingredients: ["lamb", "carrot", "cumin", "honey", "rosemary"],
    price: 2250,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1400&q=90",
    dietary: ["Gluten Free"],
    spice: 2,
    calories: 710,
    protein: 55,
    bestseller: true,
    winePairing: { name: "Syrah", note: "Pepper, dark fruit and savoury spice match the lamb." },
  },
  {
    slug: "tandoor-celeriac",
    name: "Tandoor Celeriac",
    category: "From the Fire",
    description: "Salt-baked celeriac, mustard leaf, smoked yoghurt and walnut.",
    ingredients: ["celeriac", "mustard leaf", "yoghurt", "walnut"],
    price: 1350,
    image: "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?auto=format&fit=crop&w=1400&q=90",
    dietary: ["Vegetarian", "Gluten Free", "Contains Nuts"],
    spice: 2,
    calories: 430,
    protein: 16,
    newDish: true,
    winePairing: { name: "Chenin Blanc", note: "Texture and gentle sweetness support the smoky root." },
  },
  {
    slug: "line-caught-seabass",
    name: "Line-Caught Seabass",
    category: "Mains",
    description: "Crisp seabass, leek, champagne beurre blanc and trout roe.",
    ingredients: ["seabass", "leek", "champagne", "butter", "trout roe"],
    price: 2400,
    image: "https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=1400&q=90",
    dietary: ["Gluten Free"],
    spice: 0,
    calories: 590,
    protein: 51,
    chefChoice: true,
    winePairing: { name: "White Burgundy", note: "Creamy texture and acidity echo beurre blanc." },
  },
  {
    slug: "short-rib",
    name: "48-Hour Short Rib",
    category: "Mains",
    description: "Slow beef rib, onion lacquer, potato fondant and pepper jus.",
    ingredients: ["beef", "onion", "potato", "pepper"],
    price: 2650,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1400&q=90",
    dietary: ["Gluten Free"],
    spice: 2,
    calories: 820,
    protein: 63,
    bestseller: true,
    winePairing: { name: "Cabernet Sauvignon", note: "Structure and cassis stand up to the long-cooked beef." },
  },
  {
    slug: "pumpkin-ravioli",
    name: "Pumpkin Ravioli",
    category: "Mains",
    description: "Roast pumpkin ravioli, sage butter, parmesan and toasted seeds.",
    ingredients: ["pumpkin", "pasta", "sage", "parmesan", "seeds"],
    price: 1450,
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1400&q=90",
    dietary: ["Vegetarian"],
    spice: 0,
    calories: 610,
    protein: 22,
    winePairing: { name: "Viognier", note: "Floral richness complements sweet pumpkin and sage." },
  },
  {
    slug: "green-garden",
    name: "Green Garden",
    category: "Mains",
    description: "Seasonal greens, pea miso, charred asparagus and herb broth.",
    ingredients: ["asparagus", "peas", "greens", "herbs", "miso"],
    price: 1500,
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1400&q=90",
    dietary: ["Vegetarian", "Vegan", "Gluten Free"],
    spice: 1,
    calories: 440,
    protein: 20,
    newDish: true,
    winePairing: { name: "Sauvignon Blanc", note: "Herbal lift mirrors asparagus and green broth." },
  },
  {
    slug: "burnt-honey",
    name: "Burnt Honey",
    category: "Desserts",
    description: "Burnt honey parfait, milk ice cream, sesame and bee pollen.",
    ingredients: ["honey", "milk", "sesame", "bee pollen"],
    price: 790,
    image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=1400&q=90",
    dietary: ["Vegetarian"],
    spice: 0,
    calories: 480,
    protein: 9,
    chefChoice: true,
    bestseller: true,
    winePairing: { name: "Sauternes", note: "Honeyed acidity makes the dessert feel lighter." },
  },
  {
    slug: "dark-chocolate",
    name: "Dark Chocolate",
    category: "Desserts",
    description: "70% chocolate, malt, olive oil, sea salt and cacao nib.",
    ingredients: ["dark chocolate", "malt", "olive oil", "cacao"],
    price: 850,
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1400&q=90",
    dietary: ["Vegetarian"],
    spice: 0,
    calories: 520,
    protein: 8,
    winePairing: { name: "Tawny Port", note: "Nutty oxidative notes soften dark cacao bitterness." },
  },
  {
    slug: "mango-saffron",
    name: "Mango & Saffron",
    category: "Desserts",
    description: "Alphonso mango, coconut, lime leaf, saffron and pistachio.",
    ingredients: ["mango", "coconut", "lime leaf", "saffron", "pistachio"],
    price: 820,
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1400&q=90",
    dietary: ["Vegetarian", "Gluten Free", "Contains Nuts"],
    spice: 0,
    calories: 450,
    protein: 7,
    newDish: true,
    winePairing: { name: "Moscato d'Asti", note: "Low alcohol and floral fruit work with ripe mango." },
  },
];

export function getDish(slug: string) {
  return dishes.find((dish) => dish.slug === slug);
}
